# Generated by Django 2.1.2 on 2018-10-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaPagar',
            fields=[
                ('id_baixa_pagar', models.IntegerField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.CharField(max_length=12)),
                ('data_baixa', models.CharField(max_length=12)),
                ('valor_pago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='BaixaReceber',
            fields=[
                ('id_baixa_receber', models.IntegerField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.CharField(max_length=12)),
                ('data_baixa', models.CharField(max_length=12)),
                ('valor_pago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipo_pessoa', models.CharField(max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id_conta_bancaria', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=18)),
                ('descricao', models.CharField(max_length=50)),
                ('numero_conta', models.CharField(max_length=20)),
                ('numero_agencia', models.CharField(max_length=20)),
                ('data_saldo_inicial', models.CharField(max_length=12)),
                ('saldo_inicial', models.CharField(max_length=14)),
                ('caixa', models.CharField(max_length=1)),
                ('banco', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipo_pessoa', models.CharField(max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma_pagamento', models.CharField(max_length=11)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.IntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipo_pessoa', models.CharField(max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoPagar',
            fields=[
                ('id_lancamento_pagar', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.CharField(max_length=12)),
                ('data_vencimento', models.CharField(max_length=12)),
                ('valor_titulo', models.CharField(max_length=14)),
                ('numero_documento', models.CharField(max_length=20)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Empresa')),
                ('id_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoReceber',
            fields=[
                ('id_lancamento_receber', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.CharField(max_length=12)),
                ('data_vencimento', models.CharField(max_length=12)),
                ('valor_titulo', models.CharField(max_length=14)),
                ('numero_documento', models.CharField(max_length=20)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cliente')),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id_plano_de_contas', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=18)),
                ('tipo_conta', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=50)),
                ('caixa', models.CharField(max_length=1)),
                ('banco', models.CharField(max_length=1)),
                ('cliente', models.CharField(max_length=1)),
                ('fornecedor', models.CharField(max_length=1)),
                ('entrada_recurso', models.CharField(max_length=1)),
                ('saida_recurso', models.CharField(max_length=1)),
                ('id_conta_bancaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ContaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id_tesouraria', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=14)),
                ('numero', models.CharField(max_length=15)),
                ('data_emissao', models.CharField(max_length=12)),
                ('data_vencimento', models.CharField(max_length=12)),
                ('data_disponibilidade', models.CharField(max_length=12)),
                ('id_Empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empresa')),
                ('id_clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cliente')),
                ('id_formas_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FormaDePagamento')),
                ('id_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Fornecedor')),
                ('id_plano_de_contas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PlanoDeContas')),
            ],
        ),
        migrations.AddField(
            model_name='baixareceber',
            name='id_forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FormaDePagamento'),
        ),
        migrations.AddField(
            model_name='baixareceber',
            name='id_lancamento_receber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LancamentoReceber'),
        ),
        migrations.AddField(
            model_name='baixapagar',
            name='id_forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FormaDePagamento'),
        ),
    ]
