# Generated by Django 2.0.8 on 2018-10-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaPagar',
            fields=[
                ('idBaixasPagar', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.CharField(max_length=12)),
                ('dataBaixa', models.CharField(max_length=12)),
                ('valorPago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='BaixaReceber',
            fields=[
                ('idBaixasReceber', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.CharField(max_length=12)),
                ('dataBaixa', models.CharField(max_length=12)),
                ('valorPago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idClientes', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nomeTitular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('idContasBancarias', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=18)),
                ('descricao', models.CharField(max_length=50)),
                ('numeroConta', models.CharField(max_length=20)),
                ('numeroAgencia', models.CharField(max_length=20)),
                ('dataSaldoInicial', models.CharField(max_length=12)),
                ('saldoInicial', models.CharField(max_length=14)),
                ('caixa', models.CharField(max_length=1)),
                ('banco', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('idEmpresas', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nomeTitular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFormasPagamento', models.CharField(max_length=11)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('idFornecedores', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nomeTitular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoPagar',
            fields=[
                ('idLancamentosPagar', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('dataEmissao', models.CharField(max_length=12)),
                ('dataVencimento', models.CharField(max_length=12)),
                ('valorTitulo', models.CharField(max_length=14)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('idEmpresas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Empresas')),
                ('idFornecedores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoReceber',
            fields=[
                ('idLancamentosReceber', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('dataEmissao', models.CharField(max_length=12)),
                ('dataVencimento', models.CharField(max_length=12)),
                ('valorTitulo', models.CharField(max_length=14)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('idClientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Clientes')),
                ('idEmpresas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Empresas')),
            ],
        ),
        migrations.CreateModel(
            name='PlanodeContas',
            fields=[
                ('idPlanodeContas', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=18)),
                ('tipoConta', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=50)),
                ('caixa', models.CharField(max_length=1)),
                ('banco', models.CharField(max_length=1)),
                ('cliente', models.CharField(max_length=1)),
                ('fornecedor', models.CharField(max_length=1)),
                ('entradaRecurso', models.CharField(max_length=1)),
                ('saidaRecurso', models.CharField(max_length=1)),
                ('idContasBancarias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.ContasBancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('idTesouraria', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=14)),
                ('numero', models.CharField(max_length=15)),
                ('dataEmissao', models.CharField(max_length=12)),
                ('dataVencimento', models.CharField(max_length=12)),
                ('dataDisponibilidade', models.CharField(max_length=12)),
                ('idClientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Clientes')),
                ('idEmpresas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Empresas')),
                ('idFormasPagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.FormasPagamento')),
                ('idFornecedores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Fornecedores')),
                ('idPlanodeContas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanodeContas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=22)),
                ('confirmaSenha', models.CharField(max_length=22)),
            ],
        ),
        migrations.AddField(
            model_name='baixareceber',
            name='idFormasPagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.FormasPagamento'),
        ),
        migrations.AddField(
            model_name='baixareceber',
            name='idLancamentosReceber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.LancamentoReceber'),
        ),
        migrations.AddField(
            model_name='baixapagar',
            name='idFormasPagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.FormasPagamento'),
        ),
    ]
